name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        include:
          - os: windows-latest
            c_compiler: cl
          - os: ubuntu-latest
            c_compiler: gcc
          - os: ubuntu-latest
            c_compiler: clang

    steps:
      - uses: actions/checkout@v3
      - name: get-cmake
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: "~3.23.0"

      - name: Activate VS dev prompt
        if: matrix.os == 'windows-latest'
        uses: TheMrMilchmann/setup-msvc-dev@v2
        with:
          arch: x64

      - name: Configure CMake
        run: cmake -Bbuild -GNinja -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build
